name: Say hi!
auhtor: cvesa
description: Say Hi and show time

inputs:
  who-to-greet:
    descripion: Who to say hi to? 
    default: world
outputs:
  time:
    description: The time we were friendly

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.who-to-greet }}
